Repository WordPress/twentytwentyfour, pull requests merged in 2023-10, with the labels that each got.

#522 Avoid empty headings with asterisk
  functions.php
Labels: [Type] Discussion

#531 Replace the RSVP patten with the full page RSVP landing page pattern
  patterns/page-07-rsvp-landing.php
Labels: [Type] Bug, Accessibility (a11y)

#574 Tweaks for milky style variation
  styles/fossil.json
  styles/milky.json
Labels: [Type] Bug, [Component] Style Variations

#576 Another round of pattern fixes
  patterns/centered-statement.php
  patterns/clients.php
  patterns/columns.php
  patterns/faq.php
  patterns/page-01-business-home.php
  patterns/page-03-portfolio-overview.php
  patterns/page-04-newsletter-landing.php
  patterns/page-06-writer-home.php
  patterns/page-07-rsvp-landing.php
  patterns/project-layout.php
  patterns/text-centered-cta-subscribe.php
Labels: [Type] Bug, [Component] Block Patterns

#557 Single posts: fix padding on mobile
  templates/single.html
Labels: [Status] Needs Design Feedback

#586 Tweak spacing presets on mobile
  theme.json
Labels: [Type] Enhancement

#601 Re-add area and tagName attributes to header template part calls
  README.md
  patterns/template-archive-portfolio.php
  patterns/template-archive-writer.php
  patterns/template-home-business.php
  patterns/template-home-portfolio.php
  patterns/template-home-writer.php
  patterns/template-index-portfolio.php
  patterns/template-index-writer.php
  patterns/template-search-portfolio.php
  patterns/template-search-writer.php
  patterns/template-single-portfolio.php
  templates/404.html
  templates/archive.html
  templates/index.html
  templates/page-no-title.html
  templates/page-wide.html
  templates/page-with-sidebar.html
  templates/page.html
  templates/search.html
  templates/single-with-sidebar.html
  templates/single.html
Labels: hacktoberfest

#618 Fix duplicate spacing scale bug
  theme.json
Labels: [Type] Bug

#639 Update pattern category on text-title-left-image-right
  patterns/text-title-left-image-right.php
Labels: [Type] Bug, [Component] Block Patterns

#633 Add services categories to related patterns
  patterns/pricing.php
  patterns/services-cta.php
Labels: [Component] Block Patterns

#635 Rename footers appropriately
  patterns/footer-centered-logo-nav.php
  patterns/footer-colophon-3-col.php
  patterns/footer.php
Labels: [Type] Bug, [Component] Block Patterns

#636 Remove core/post-content from the Writer Home pattern
  patterns/page-06-writer-home.php
Labels: [Type] Enhancement

#638 Add separate RSVP content pattern and fullscreen page pattern
  patterns/page-07-rsvp-landing.php
  patterns/rsvp.php
Labels: [Type] Enhancement, [Component] Block Patterns

#631 Add page pattern category
  functions.php
  patterns/page-01-business-home.php
  patterns/page-02-business-about.php
  patterns/page-03-portfolio-overview.php
  patterns/page-04-newsletter-landing.php
  patterns/page-05-portfolio-home.php
Labels: [Type] Enhancement, [Component] Block Patterns

#630 Add offset image grid patterns
  patterns/gallery-offset-image-grid-2-col.php
  patterns/gallery-offset-image-grid-3-col.php
  patterns/gallery-offset-image-grid.php
Labels: [Type] Enhancement, [Component] Block Patterns

#626 Move a couple patterns to theme.json
  patterns/clients.php
  patterns/columns.php
  patterns/page-02-business-about.php
  theme.json
Labels: [Type] Enhancement, [Component] Block Patterns

#604 Adjust single with sidebar template
  templates/single-with-sidebar.html
Labels: hacktoberfest

#648 Fix RSVP patterns
  patterns/page-07-rsvp-landing.php
  patterns/rsvp.php
Labels: [Type] Bug

#647 Fix hero area orphaned text
  patterns/hero.php
  theme.json
Labels: [Type] Bug

#646 Remove button border and fix outline variation padding inconsistencies
  styles/fossil.json
  theme.json
Labels: [Type] Bug, [Component] theme.json

#669 Reset vertical margins for more Patterns
  patterns/gallery-offset-image-grid-2-col.php
  patterns/gallery-offset-image-grid-3-col.php
  patterns/gallery-offset-image-grid.php
  patterns/testimonial-centered.php
  patterns/text-centered-cta-subscribe.php
Labels: [Type] Bug, [Component] Block Patterns

#690 Minor color contrast fix
  patterns/cta-services-image-left.php
  patterns/text-faq.php
Labels: [Type] Bug

#709 Remove index as from unrelated templates
  patterns/template-home-business.php
  patterns/template-home-portfolio.php
Labels: [Type] Bug, [Component] Templates
